import React, { useState, useEffect, useRef } from 'react';
import { Plus, Trash2, ArrowLeft, Save, Sparkles, Building, User, CheckCircle2, RotateCcw, ShieldCheck, Repeat, Calendar } from 'lucide-react';
import { Invoice, InvoiceItem, Client, UserProfile, InvoiceTemplate, RecurringFrequency } from '../types';

interface InvoiceFormViewProps {
  clients?: Client[];
  templates?: InvoiceTemplate[];
  userProfile?: UserProfile;
  initialInvoice?: Invoice;
  invoice?: Invoice;
  onSave?: (invoiceData: Omit<Invoice, 'id' | 'createdAt' | 'updatedAt'>, existingId?: string) => void;
  onSubmit?: (invoiceData: any) => void;
  onCancel?: () => void;
  onNavigate?: (route: string) => void;
}

const DRAFT_STORAGE_KEY = 'self_employed_invoice_draft_v1';

export const InvoiceFormView: React.FC<InvoiceFormViewProps> = ({
  clients = [],
  templates = [],
  userProfile,
  initialInvoice,
  invoice,
  onSave,
  onSubmit,
  onCancel,
  onNavigate
}) => {
  const activeInvoice = initialInvoice || invoice;
  const isEditingExisting = Boolean(activeInvoice?.id);
  const safeClients = clients || [];
  const safeTemplates = templates || [];
  const [formError, setFormError] = useState<string | null>(null);
  const [lastAutoSavedAt, setLastAutoSavedAt] = useState<string | null>(null);
  const [draftRestoredBanner, setDraftRestoredBanner] = useState<boolean>(false);

  const handleCancel = () => {
    if (onCancel) {
      onCancel();
    } else if (onNavigate) {
      onNavigate('/invoices');
    }
  };

  // Initial state setup with local draft restore support
  const [selectedClientId, setSelectedClientId] = useState<string>(() => {
    if (activeInvoice?.clientId) return activeInvoice.clientId;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.selectedClientId) return parsed.selectedClientId;
        }
      } catch (e) {}
    }
    return safeClients.length > 0 ? safeClients[0].id : '';
  });

  const selectedClient = safeClients.find((c) => c.id === selectedClientId) || safeClients[0];

  const [number, setNumber] = useState<string>(() => {
    if (activeInvoice?.number) return activeInvoice.number;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.number) return parsed.number;
        }
      } catch (e) {}
    }
    return `СЧ-2026-00${Math.floor(Math.random() * 90 + 10)}`;
  });

  const [date, setDate] = useState<string>(() => {
    if (activeInvoice?.date) return activeInvoice.date;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.date) return parsed.date;
        }
      } catch (e) {}
    }
    return new Date().toISOString().split('T')[0];
  });

  const [dueDate, setDueDate] = useState<string>(() => {
    if (activeInvoice?.dueDate) return activeInvoice.dueDate;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.dueDate) return parsed.dueDate;
        }
      } catch (e) {}
    }
    return new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0];
  });

  // Recurring state
  const [isRecurring, setIsRecurring] = useState<boolean>(() => {
    if (activeInvoice?.isRecurring !== undefined) return activeInvoice.isRecurring;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.isRecurring !== undefined) return parsed.isRecurring;
        }
      } catch (e) {}
    }
    return false;
  });

  const [recurringFrequency, setRecurringFrequency] = useState<RecurringFrequency>(() => {
    if (activeInvoice?.recurringFrequency) return activeInvoice.recurringFrequency;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.recurringFrequency) return parsed.recurringFrequency;
        }
      } catch (e) {}
    }
    return 'monthly';
  });

  const [autoGenerateDrafts, setAutoGenerateDrafts] = useState<boolean>(() => {
    if (activeInvoice?.autoGenerateDrafts !== undefined) return activeInvoice.autoGenerateDrafts;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.autoGenerateDrafts !== undefined) return parsed.autoGenerateDrafts;
        }
      } catch (e) {}
    }
    return true;
  });

  const computeNextRecurringDate = (baseDateStr: string, freq: RecurringFrequency): string => {
    const d = new Date(baseDateStr || Date.now());
    if (isNaN(d.getTime())) return new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0];
    if (freq === 'weekly') {
      d.setDate(d.getDate() + 7);
    } else if (freq === 'quarterly') {
      d.setMonth(d.getMonth() + 3);
    } else {
      d.setMonth(d.getMonth() + 1);
    }
    return d.toISOString().split('T')[0];
  };

  const nextRecurringDate = computeNextRecurringDate(date, recurringFrequency);

  const [items, setItems] = useState<InvoiceItem[]>(() => {
    if (activeInvoice?.items && activeInvoice.items.length > 0) return activeInvoice.items;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.items && Array.isArray(parsed.items) && parsed.items.length > 0) {
            return parsed.items;
          }
        }
      } catch (e) {}
    }
    return [
      { id: 'itm_1', description: 'Разработка UX/UI дизайна прототипа', quantity: 1, unitPrice: 35000, total: 35000 }
    ];
  });

  const defaultNotesVal = userProfile?.invoiceSettings?.defaultNotes || 'Без НДС. Налог на профессиональный доход (НПД).';
  const [notes, setNotes] = useState<string>(() => {
    if (activeInvoice?.notes) return activeInvoice.notes;
    if (!isEditingExisting) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.notes !== undefined) return parsed.notes;
        }
      } catch (e) {}
    }
    return defaultNotesVal;
  });

  // Check if draft was restored on first mount
  const isInitialMount = useRef(true);
  useEffect(() => {
    if (!isEditingExisting && isInitialMount.current) {
      try {
        const saved = localStorage.getItem(DRAFT_STORAGE_KEY);
        if (saved) {
          const parsed = JSON.parse(saved);
          if (parsed.savedAt) {
            setLastAutoSavedAt(parsed.savedAt);
            setDraftRestoredBanner(true);
          }
        }
      } catch (e) {}
    }
    isInitialMount.current = false;
  }, [isEditingExisting]);

  // Keep a ref of latest form data for the periodic interval
  const latestDraftRef = useRef({
    selectedClientId,
    number,
    date,
    dueDate,
    items,
    notes,
    isRecurring,
    recurringFrequency,
    autoGenerateDrafts
  });

  useEffect(() => {
    latestDraftRef.current = {
      selectedClientId,
      number,
      date,
      dueDate,
      items,
      notes,
      isRecurring,
      recurringFrequency,
      autoGenerateDrafts
    };
  }, [selectedClientId, number, date, dueDate, items, notes, isRecurring, recurringFrequency, autoGenerateDrafts]);

  // Periodic 10-second auto-save interval
  useEffect(() => {
    if (isEditingExisting) return;

    const performSave = () => {
      try {
        const currentTime = new Date().toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
        const draftPayload = {
          ...latestDraftRef.current,
          savedAt: currentTime
        };
        localStorage.setItem(DRAFT_STORAGE_KEY, JSON.stringify(draftPayload));
        setLastAutoSavedAt(currentTime);
      } catch (err) {
        console.error('Error auto-saving invoice draft:', err);
      }
    };

    // 10 second periodic interval timer
    const interval = setInterval(performSave, 10000);

    // Also debounced save on changes
    const debounceTimer = setTimeout(performSave, 500);

    return () => {
      clearInterval(interval);
      clearTimeout(debounceTimer);
    };
  }, [isEditingExisting, selectedClientId, number, date, dueDate, items, notes, isRecurring, recurringFrequency, autoGenerateDrafts]);

  const handleClearDraft = () => {
    try {
      localStorage.removeItem(DRAFT_STORAGE_KEY);
    } catch (e) {}
    setDraftRestoredBanner(false);
    setLastAutoSavedAt(null);
    setNumber(`СЧ-2026-00${Math.floor(Math.random() * 90 + 10)}`);
    setDate(new Date().toISOString().split('T')[0]);
    setDueDate(new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0]);
    setSelectedClientId(safeClients.length > 0 ? safeClients[0].id : '');
    setIsRecurring(false);
    setRecurringFrequency('monthly');
    setAutoGenerateDrafts(true);
    setItems([
      { id: 'itm_1', description: 'Разработка UX/UI дизайна прототипа', quantity: 1, unitPrice: 35000, total: 35000 }
    ]);
    setNotes(defaultNotesVal);
  };

  // Item helpers
  const handleAddItem = () => {
    setItems([
      ...items,
      { id: `itm_${Date.now()}`, description: '', quantity: 1, unitPrice: 5000, total: 5000 }
    ]);
  };

  const handleRemoveItem = (id: string) => {
    if (items.length === 1) return;
    setItems(items.filter((i) => i.id !== id));
  };

  const handleItemChange = (id: string, field: keyof InvoiceItem, value: any) => {
    setItems(
      items.map((item) => {
        if (item.id !== id) return item;
        const updated = { ...item, [field]: value };
        if (field === 'quantity' || field === 'unitPrice') {
          updated.total = Number(updated.quantity || 0) * Number(updated.unitPrice || 0);
        }
        return updated;
      })
    );
  };

  const applyTemplate = (template: InvoiceTemplate) => {
    const newItems: InvoiceItem[] = template.items.map((it, idx) => ({
      id: `itm_tmpl_${idx}_${Date.now()}`,
      description: it.description,
      quantity: it.quantity,
      unitPrice: it.unitPrice,
      total: it.quantity * it.unitPrice
    }));
    setItems(newItems);
  };

  const subtotal = items.reduce((sum, item) => sum + item.total, 0);
  const clientType = selectedClient ? selectedClient.type : 'legal';
  // Tax calculation NPD
  const taxRatePercent = clientType === 'legal' ? 6 : 4;
  const taxAmount = Math.round(subtotal * (taxRatePercent / 100));
  const total = subtotal;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedClient) {
      setFormError('Пожалуйста, выберите или создайте клиента');
      return;
    }
    setFormError(null);

    const invoiceData = {
      number,
      date,
      dueDate,
      clientId: selectedClient.id,
      clientName: selectedClient.name,
      clientType: selectedClient.type,
      clientInn: selectedClient.inn,
      clientEmail: selectedClient.email,
      items,
      subtotal,
      taxRate: 0,
      taxAmount,
      total,
      status: activeInvoice ? activeInvoice.status : ('issued' as const),
      notes,
      isRecurring,
      recurringFrequency: isRecurring ? recurringFrequency : undefined,
      nextRecurringDate: isRecurring ? nextRecurringDate : undefined,
      autoGenerateDrafts: isRecurring ? autoGenerateDrafts : undefined,
      paymentLink: activeInvoice?.paymentLink || `https://sbp.nspk.ru/pay?id=${Date.now()}`,
      token: activeInvoice?.token || `tok_${Math.random().toString(36).substring(2, 11)}`
    };

    // Clean up draft on successful creation
    try {
      localStorage.removeItem(DRAFT_STORAGE_KEY);
    } catch (err) {}

    if (onSubmit) {
      onSubmit(invoiceData);
    } else if (onSave) {
      onSave(invoiceData, activeInvoice?.id);
      if (onCancel) {
        onCancel();
      } else if (onNavigate) {
        onNavigate('/invoices');
      }
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center space-x-3">
          <button
            type="button"
            onClick={handleCancel}
            className="px-3 py-2 text-xs font-bold text-[var(--text-secondary)] hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center space-x-1 cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4 text-[var(--text-secondary)]" />
            <span>Отмена</span>
          </button>
          <h2 className="text-xl sm:text-2xl font-bold text-[var(--text-primary)]">
            {activeInvoice ? 'Редактирование счета' : 'Создание счета на оплату'}
          </h2>
        </div>

        {/* Auto-save draft status badge */}
        {!isEditingExisting && (
          <div className="flex items-center space-x-2 text-xs">
            <div className="flex items-center space-x-1.5 px-3 py-1.5 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 rounded-xl border border-emerald-500/20 font-bold">
              <ShieldCheck className="w-4 h-4 text-emerald-500 shrink-0" />
              <span>
                {lastAutoSavedAt ? `Автосохранено в ${lastAutoSavedAt}` : 'Автосохранение активно'}
              </span>
            </div>
            {lastAutoSavedAt && (
              <button
                type="button"
                onClick={handleClearDraft}
                title="Очистить и сбросить форму"
                className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-[var(--text-secondary)] font-bold rounded-xl flex items-center space-x-1 cursor-pointer"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span className="text-[11px]">Сбросить</span>
              </button>
            )}
          </div>
        )}
      </div>

      {/* Restored draft notice */}
      {draftRestoredBanner && (
        <div className="p-3.5 bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900 rounded-xl flex items-center justify-between text-xs text-blue-900 dark:text-blue-200">
          <div className="flex items-center space-x-2">
            <CheckCircle2 className="w-4 h-4 text-blue-600 shrink-0" />
            <span>
              <strong>Восстановлены данные из автосохраненного черновика.</strong> Ваши предыдущие изменения не потерялись.
            </span>
          </div>
          <button
            type="button"
            onClick={() => setDraftRestoredBanner(false)}
            className="text-[11px] font-bold text-blue-600 dark:text-blue-400 hover:underline cursor-pointer ml-2"
          >
            Понятно
          </button>
        </div>
      )}

      {formError && (
        <div className="p-3 bg-rose-50 border border-rose-200 text-rose-700 rounded-xl text-xs font-bold">
          {formError}
        </div>
      )}

      {/* Templates Selector Pill */}
      {safeTemplates.length > 0 && (
        <div className="custom-card p-4 space-y-2">
          <span className="text-xs font-bold text-[var(--text-secondary)] flex items-center">
            <Sparkles className="w-3.5 h-3.5 mr-1 text-[#E67E22]" />
            Быстрое заполнение по шаблону:
          </span>
          <div className="flex flex-wrap gap-2">
            {safeTemplates.map((tmpl) => (
              <button
                key={tmpl.id}
                type="button"
                onClick={() => applyTemplate(tmpl)}
                className="px-3.5 py-1.5 text-xs bg-[var(--bg-main)] hover:bg-[#E67E22]/10 hover:border-[#E67E22] border border-[var(--border-subtle)] rounded-lg text-[var(--text-primary)] font-bold transition-colors cursor-pointer"
              >
                + {tmpl.title}
              </button>
            ))}
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="custom-card p-6 space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-bold text-[var(--text-primary)] mb-1">Номер счета *</label>
              <input
                type="text"
                value={number}
                onChange={(e) => setNumber(e.target.value)}
                required
                className="w-full px-3 py-2 text-sm bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl font-medium text-[var(--text-primary)]"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-[var(--text-primary)] mb-1">Дата выставления</label>
              <input
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                required
                className="w-full px-3 py-2 text-sm bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl font-medium text-[var(--text-primary)]"
              />
            </div>
            <div>
              <label className="block text-xs font-bold text-[var(--text-primary)] mb-1">Оплатить до (дедлайн)</label>
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                required
                className="w-full px-3 py-2 text-sm bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl font-medium text-[var(--text-primary)]"
              />
            </div>
          </div>

          {/* Client selector */}
          <div className="pt-2 border-t border-[var(--border-subtle)]">
            <div className="flex justify-between items-center mb-1">
              <label className="block text-xs font-bold text-[var(--text-primary)]">Выберите клиента *</label>
              <button
                type="button"
                onClick={() => onNavigate && onNavigate('/clients')}
                className="text-xs text-[#E67E22] font-bold hover:underline cursor-pointer"
              >
                + Добавить нового клиента
              </button>
            </div>
            <select
              value={selectedClientId}
              onChange={(e) => setSelectedClientId(e.target.value)}
              className="w-full px-3 py-2 text-sm bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl font-medium text-[var(--text-primary)]"
            >
              {safeClients.map((cli) => (
                <option key={cli.id} value={cli.id}>
                  {cli.name} ({cli.type === 'legal' ? 'Юрлицо/ИП — Налог 6%' : 'Физлицо — Налог 4%'})
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Recurring Invoice Settings Toggle */}
        <div className="custom-card p-5 space-y-4 border border-amber-500/20 bg-gradient-to-br from-[var(--bg-card)] to-amber-500/5">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2.5">
              <div className="p-2 rounded-xl bg-[#E67E22]/10 text-[#E67E22]">
                <Repeat className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-extrabold text-sm text-[var(--text-primary)]">
                  Регулярный / Периодический счет
                </h3>
                <p className="text-[11px] text-[var(--text-secondary)]">
                  Автоматическая генерация счетов для постоянных клиентов и подписок
                </p>
              </div>
            </div>
            <label className="relative inline-flex items-center cursor-pointer">
              <input
                type="checkbox"
                checked={isRecurring}
                onChange={(e) => setIsRecurring(e.target.checked)}
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-slate-300 dark:bg-slate-700 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[#E67E22]"></div>
            </label>
          </div>

          {isRecurring && (
            <div className="space-y-3 pt-2 border-t border-[var(--border-subtle)]">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-[var(--text-secondary)] mb-1">
                    Частота повторения
                  </label>
                  <select
                    value={recurringFrequency}
                    onChange={(e) => setRecurringFrequency(e.target.value as RecurringFrequency)}
                    className="w-full px-3 py-2 text-xs bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl font-bold text-[var(--text-primary)] focus:border-[#E67E22] outline-none"
                  >
                    <option value="weekly">Еженедельно (каждые 7 дней)</option>
                    <option value="monthly">Ежемесячно (абонентская плата)</option>
                    <option value="quarterly">Ежеквартально (раз в 3 месяца)</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-[var(--text-secondary)] mb-1">
                    Дата следующего авто-счета
                  </label>
                  <div className="flex items-center space-x-2 px-3 py-2 bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl text-xs font-bold text-[#E67E22]">
                    <Calendar className="w-4 h-4 text-[#E67E22] shrink-0" />
                    <span>{nextRecurringDate}</span>
                  </div>
                </div>
              </div>

              <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-xl flex items-center justify-between">
                <div className="space-y-0.5 pr-2">
                  <span className="text-xs font-bold text-[var(--text-primary)] block">
                    Создавать новый черновик счета автоматически
                  </span>
                  <span className="text-[11px] text-[var(--text-secondary)]">
                    Черновик появится в списке счетов к нужной дате с уведомлением
                  </span>
                </div>
                <input
                  type="checkbox"
                  checked={autoGenerateDrafts}
                  onChange={(e) => setAutoGenerateDrafts(e.target.checked)}
                  className="w-4 h-4 rounded text-[#E67E22] accent-[#E67E22] cursor-pointer"
                />
              </div>
            </div>
          )}
        </div>

        {/* Invoice Items Table */}
        <div className="custom-card p-6 space-y-4">
          <h3 className="font-bold text-sm text-[var(--text-primary)]">Список работ и услуг</h3>

          <div className="space-y-3">
            {items.map((item) => (
              <div key={item.id} className="grid grid-cols-12 gap-2 items-center bg-[var(--bg-main)] p-3 rounded-xl border border-[var(--border-subtle)] text-xs">
                <div className="col-span-12 sm:col-span-6">
                  <label className="block text-[10px] font-bold text-[var(--text-muted)] mb-0.5">Наименование работы/услуги</label>
                  <input
                    type="text"
                    value={item.description}
                    onChange={(e) => handleItemChange(item.id, 'description', e.target.value)}
                    placeholder="Например: Разработка макета сайта"
                    required
                    className="w-full px-2.5 py-2 bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-lg text-[var(--text-primary)] font-medium"
                  />
                </div>

                <div className="col-span-4 sm:col-span-2">
                  <label className="block text-[10px] font-bold text-[var(--text-muted)] mb-0.5">Кол-во</label>
                  <input
                    type="number"
                    min="1"
                    value={item.quantity}
                    onChange={(e) => handleItemChange(item.id, 'quantity', Number(e.target.value))}
                    className="w-full px-2.5 py-2 bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-lg text-center text-[var(--text-primary)] font-bold"
                  />
                </div>

                <div className="col-span-5 sm:col-span-3">
                  <label className="block text-[10px] font-bold text-[var(--text-muted)] mb-0.5">Цена (₽)</label>
                  <input
                    type="number"
                    min="0"
                    step="500"
                    value={item.unitPrice}
                    onChange={(e) => handleItemChange(item.id, 'unitPrice', Number(e.target.value))}
                    className="w-full px-2.5 py-2 bg-[var(--bg-surface)] border border-[var(--border-subtle)] rounded-lg text-right text-[var(--text-primary)] font-bold"
                  />
                </div>

                <div className="col-span-3 sm:col-span-1 flex justify-end">
                  <button
                    type="button"
                    onClick={() => handleRemoveItem(item.id)}
                    className="p-2 text-[var(--text-secondary)] hover:text-rose-600 hover:bg-rose-100 rounded-lg cursor-pointer"
                  >
                    <Trash2 className="w-4 h-4 text-rose-500" />
                  </button>
                </div>
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={handleAddItem}
            className="px-3.5 py-2 text-xs bg-[var(--bg-main)] hover:bg-slate-200 dark:hover:bg-slate-800 border border-[var(--border-subtle)] font-bold text-[var(--text-primary)] rounded-xl flex items-center space-x-1 cursor-pointer"
          >
            <Plus className="w-4 h-4 text-[var(--text-primary)]" />
            <span>+ Добавить позицию</span>
          </button>
        </div>

        {/* Totals & Notes */}
        <div className="custom-card p-6 space-y-4">
          <div>
            <label className="block text-xs font-bold text-[var(--text-primary)] mb-1">Условия и примечания</label>
            <textarea
              rows={3}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full px-3 py-2 text-xs bg-[var(--bg-main)] border border-[var(--border-subtle)] rounded-xl text-[var(--text-primary)] font-medium"
            />
          </div>

          <div className="p-4 bg-slate-100 dark:bg-slate-800/80 rounded-xl space-y-2 text-xs text-[var(--text-primary)]">
            <div className="flex justify-between font-bold">
              <span>Итого по услугам:</span>
              <span className="text-[var(--text-primary)]">{subtotal.toLocaleString('ru-RU')} ₽</span>
            </div>
            <div className="flex justify-between text-amber-700 dark:text-amber-300 font-bold">
              <span>Расчетный налог НПД ({taxRatePercent}%):</span>
              <span>{taxAmount.toLocaleString('ru-RU')} ₽</span>
            </div>
            <div className="border-t border-[var(--border-subtle)] pt-2 flex justify-between text-base font-extrabold text-[var(--text-primary)]">
              <span>Всего к уплате клиентом:</span>
              <span>{total.toLocaleString('ru-RU')} ₽</span>
            </div>
          </div>

          <button
            type="submit"
            className="w-full py-3.5 bg-[#E67E22] hover:bg-[#D35400] text-white font-extrabold rounded-xl shadow-lg flex items-center justify-center space-x-2 cursor-pointer"
          >
            <Save className="w-4 h-4 text-white" />
            <span>Сохранить и выставить счет</span>
          </button>
        </div>
      </form>
    </div>
  );
};

