import React, { useState, useEffect } from 'react';
import { UserProfile, Invoice, Client, Task, AuthUser, CalendarEvent, InvoiceTemplate, ActivityLog } from './types';
import {
  loadUserProfile,
  saveUserProfile,
  loadInvoices,
  saveInvoices,
  loadClients,
  saveClients,
  loadTasks,
  saveTasks,
  loadEvents,
  saveEvents,
  loadActivityLogs,
  loadTemplates,
  calculateNpdTax,
  getMockAuthUser,
  setMockAuthUser,
  storage
} from './utils/storage';

// Localization Context
import { LocalizationProvider, useLanguage } from './context/LocalizationContext';

// Layout Components
import { Navbar } from './components/Navbar';
import { Sidebar } from './components/Sidebar';
import { KeyboardShortcutsModal } from './components/KeyboardShortcutsModal';
import { useKeyboardShortcuts } from './hooks/useKeyboardShortcuts';

// Views
import { LandingView } from './views/LandingView';
import { LoginView } from './views/LoginView';
import { RegisterView } from './views/RegisterView';
import { DashboardView } from './views/DashboardView';
import { InvoicesView } from './views/InvoicesView';
import { InvoiceDetailView } from './views/InvoiceDetailView';
import { InvoiceFormView } from './views/InvoiceFormView';
import { PublicInvoiceView } from './views/PublicInvoiceView';
import { ClientsView } from './views/ClientsView';
import { TasksView } from './views/TasksView';
import { TaxCalculatorView } from './views/TaxCalculatorView';
import { ReportsView } from './views/ReportsView';
import { BookingView } from './views/BookingView';
import { SettingsView } from './views/SettingsView';
import { AnalyticsView } from './views/AnalyticsView';
import { CalendarView } from './views/CalendarView';
import { DevToolsView } from './views/DevToolsView';

const MainAppContent: React.FC = () => {
  const { t, language } = useLanguage();

  // Auth state
  const [currentUser, setCurrentUser] = useState<AuthUser | null>(getMockAuthUser());

  // App core data state
  const [profile, setProfile] = useState<UserProfile>(loadUserProfile());
  const [invoices, setInvoices] = useState<Invoice[]>(loadInvoices());
  const [clients, setClients] = useState<Client[]>(loadClients());
  const [tasks, setTasks] = useState<Task[]>(loadTasks());
  const [events, setEvents] = useState<CalendarEvent[]>(loadEvents());
  const [activityLogs] = useState<ActivityLog[]>(loadActivityLogs());
  const [templates] = useState<InvoiceTemplate[]>(loadTemplates());

  // Theme & Navigation
  const [isDarkMode, setIsDarkMode] = useState<boolean>(false);
  const [currentRoute, setCurrentRoute] = useState<string>(currentUser ? '/dashboard' : '/landing');

  // Active items state for details/editing
  const [selectedInvoiceId, setSelectedInvoiceId] = useState<string | null>(null);
  const [isShortcutsOpen, setIsShortcutsOpen] = useState<boolean>(false);

  // Global Keyboard Shortcuts
  const { sequenceActive, sequenceKey } = useKeyboardShortcuts(
    (route) => navigateTo(route),
    () => navigateTo('/invoices/create'),
    () => setIsShortcutsOpen((prev) => !prev)
  );

  // Auto-generate drafts for recurring invoices
  useEffect(() => {
    const recurringInvoices = invoices.filter((i) => i.isRecurring && i.autoGenerateDrafts);
    if (recurringInvoices.length === 0) return;

    let hasNewDrafts = false;
    const newDrafts: Invoice[] = [];

    const now = new Date();
    const currentMonthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

    recurringInvoices.forEach((rec) => {
      // Check if a child draft for current month was already generated
      const draftExists = invoices.some(
        (inv) =>
          inv.id !== rec.id &&
          inv.clientId === rec.clientId &&
          inv.status === 'draft' &&
          inv.createdAt.startsWith(currentMonthKey)
      );

      if (!draftExists) {
        hasNewDrafts = true;
        const generatedDraft: Invoice = {
          ...rec,
          id: `inv-rec-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
          number: `СЧ-${now.getFullYear()}-${Math.floor(200 + Math.random() * 800)}`,
          date: now.toISOString().split('T')[0],
          status: 'draft',
          createdAt: now.toISOString(),
          isRecurring: false,
          publicToken: `token-${Math.random().toString(36).substring(2, 9)}`
        };
        newDrafts.push(generatedDraft);
      }
    });

    if (hasNewDrafts && newDrafts.length > 0) {
      setInvoices((prev) => [...newDrafts, ...prev]);
    }
  }, []);

  // Sync state to LocalStorage
  useEffect(() => {
    saveUserProfile(profile);
  }, [profile]);

  useEffect(() => {
    saveInvoices(invoices);
  }, [invoices]);

  useEffect(() => {
    saveClients(clients);
  }, [clients]);

  useEffect(() => {
    saveTasks(tasks);
  }, [tasks]);

  useEffect(() => {
    saveEvents(events);
  }, [events]);

  // Ensure Dark mode is permanently applied to html root
  useEffect(() => {
    document.documentElement.classList.add('dark');
  }, []);

  // Auth Handlers
  const handleLogin = (user: AuthUser) => {
    setCurrentUser(user);
    setMockAuthUser(user);
    setCurrentRoute('/dashboard');
  };

  const handleLogout = () => {
    setCurrentUser(null);
    setMockAuthUser(null);
    setCurrentRoute('/landing');
  };

  // Navigation Helper
  const navigateTo = (route: string, id?: string) => {
    if (!route) return;
    if (id) {
      setSelectedInvoiceId(id);
    }
    setCurrentRoute(route);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  // Invoices Handlers
  const handleSaveInvoice = (invoiceData: Partial<Invoice>) => {
    if (invoiceData.id && invoices.some((i) => i.id === invoiceData.id)) {
      setInvoices((prev) =>
        prev.map((i) => (i.id === invoiceData.id ? ({ ...i, ...invoiceData } as Invoice) : i))
      );
    } else {
      const newInvoice: Invoice = {
        id: `inv-${Date.now()}`,
        number: invoiceData.number || `СЧ-2026-${Math.floor(100 + Math.random() * 900)}`,
        date: invoiceData.date || new Date().toISOString().split('T')[0],
        dueDate: invoiceData.dueDate || new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
        clientId: invoiceData.clientId || 'client-1',
        clientName: invoiceData.clientName || 'Контрагент',
        clientInn: invoiceData.clientInn || '',
        clientType: invoiceData.clientType || 'legal',
        items: invoiceData.items || [],
        subtotal: invoiceData.subtotal || 0,
        taxRate: invoiceData.taxRate || (invoiceData.clientType === 'individual' ? 4 : 6),
        taxAmount: invoiceData.taxAmount || 0,
        total: invoiceData.total || 0,
        status: invoiceData.status || 'draft',
        notes: invoiceData.notes || '',
        publicToken: `token-${Math.random().toString(36).substring(2, 9)}`,
        createdAt: new Date().toISOString(),
        isRecurring: invoiceData.isRecurring || false,
        recurringFrequency: invoiceData.recurringFrequency,
        autoGenerateDrafts: invoiceData.autoGenerateDrafts
      };
      setInvoices((prev) => [newInvoice, ...prev]);
    }
    navigateTo('/invoices');
  };

  const handleDeleteInvoice = (id: string) => {
    setInvoices((prev) => prev.filter((i) => i.id !== id));
  };

  const handleDuplicateInvoice = (invoice: Invoice) => {
    const duplicated: Invoice = {
      ...invoice,
      id: `inv-${Date.now()}`,
      number: `СЧ-${new Date().getFullYear()}-${Math.floor(100 + Math.random() * 900)}`,
      date: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
      status: 'draft',
      createdAt: new Date().toISOString(),
      publicToken: `token-${Math.random().toString(36).substring(2, 9)}`
    };
    setInvoices((prev) => [duplicated, ...prev]);
    navigateTo('/invoices');
  };

  const handleMarkPaid = (id: string) => {
    setInvoices((prev) =>
      prev.map((i) => (i.id === id ? { ...i, status: 'paid' as const } : i))
    );
  };

  // Clients Handlers
  const handleSaveClient = (clientData: Partial<Client>) => {
    if (clientData.id && clients.some((c) => c.id === clientData.id)) {
      setClients((prev) =>
        prev.map((c) => (c.id === clientData.id ? ({ ...c, ...clientData } as Client) : c))
      );
    } else {
      const newClient: Client = {
        id: `client-${Date.now()}`,
        name: clientData.name || 'Новый клиент',
        type: clientData.type || 'legal',
        inn: clientData.inn || '',
        email: clientData.email || '',
        phone: clientData.phone || '',
        address: clientData.address || '',
        tags: clientData.tags || [],
        totalLtv: 0,
        createdAt: new Date().toISOString().split('T')[0]
      };
      setClients((prev) => [newClient, ...prev]);
    }
  };

  const handleDeleteClient = (id: string) => {
    setClients((prev) => prev.filter((c) => c.id !== id));
  };

  // Task Handlers
  const handleSaveTask = (taskData: Partial<Task>) => {
    if (taskData.id && tasks.some((t) => t.id === taskData.id)) {
      setTasks((prev) =>
        prev.map((t) => (t.id === taskData.id ? ({ ...t, ...taskData } as Task) : t))
      );
    } else {
      const newTask: Task = {
        id: `task-${Date.now()}`,
        title: taskData.title || 'Новая задача',
        description: taskData.description || '',
        status: taskData.status || 'todo',
        priority: taskData.priority || 'medium',
        deadline: taskData.deadline || taskData.dueDate || new Date().toISOString().split('T')[0],
        dueDate: taskData.dueDate || taskData.deadline || new Date().toISOString().split('T')[0],
        clientId: taskData.clientId,
        clientName: taskData.clientName,
        loggedHours: taskData.loggedHours || 0,
        estimatedHours: taskData.estimatedHours || 0,
        createdAt: new Date().toISOString()
      };
      setTasks((prev) => [newTask, ...prev]);
    }
  };

  const handleUpdateTask = (updated: Task) => {
    setTasks(tasks.map((t) => (t.id === updated.id ? updated : t)));
  };

  const handleDeleteTask = (id: string) => {
    setTasks(tasks.filter((t) => t.id !== id));
  };

  // Calendar Event Handlers
  const handleSaveEvent = (event: CalendarEvent) => {
    setEvents((prev) => {
      const idx = prev.findIndex((e) => e.id === event.id);
      if (idx >= 0) {
        const copy = [...prev];
        copy[idx] = event;
        return copy;
      }
      return [event, ...prev];
    });
  };

  const handleDeleteEvent = (id: string) => {
    setEvents((prev) => prev.filter((e) => e.id !== id));
  };

  const handleSaveProfile = (updatedProfile: UserProfile) => {
    setProfile(updatedProfile);
    saveUserProfile(updatedProfile);
    if (currentUser) {
      setCurrentUser({
        ...currentUser,
        fullName: updatedProfile.fullName,
        email: updatedProfile.email,
        occupation: updatedProfile.occupation,
        profession: updatedProfile.profession,
        isSelfEmployed: updatedProfile.isSelfEmployed
      });
    }
  };

  const handleResetData = () => {
    storage.resetToMockData();
  };

  // Tax calculations result
  const taxData = calculateNpdTax(invoices);

  const activeRoute = currentRoute || '/landing';

  // Handle Public Invoice Link Routing
  if (activeRoute.startsWith('/public/invoice/') || activeRoute.startsWith('/invoices/public/')) {
    const token = activeRoute.includes('/public/invoice/')
      ? activeRoute.split('/public/invoice/')[1]
      : activeRoute.split('/invoices/public/')[1];
    const pubInvoice = invoices.find((i) => i.publicToken === token || i.id === token || i.token === token);

    return (
      <div className="min-h-screen bg-[#F8FAFC] text-slate-800 font-sans">
        <header className="bg-[#2C3E50] text-white p-4 flex items-center justify-between border-b border-slate-700">
          <div className="flex items-center space-x-2 font-bold text-sm">
            <span className="bg-[#E67E22] text-white px-2 py-0.5 rounded text-xs font-extrabold">НПД</span>
            <span>{t('auto.smartorganizer')}</span>
          </div>
          <button
            onClick={() => navigateTo('/landing')}
            className="text-xs text-slate-300 hover:text-white underline cursor-pointer"
          >
            {t('auto.opendashboard')}
          </button>
        </header>

        <PublicInvoiceView
          invoice={pubInvoice}
          userProfile={profile}
          onMarkPaid={handleMarkPaid}
        />
      </div>
    );
  }

  // Handle Public Landing / Login / Register pages
  if (activeRoute === '/landing' || activeRoute === '/') {
    return (
      <LandingView
        onNavigate={navigateTo}
        userProfile={profile}
        isDarkMode={isDarkMode}
        onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
      />
    );
  }

  if (activeRoute === '/login') {
    return (
      <LoginView
        onLogin={handleLogin}
        onLoginSuccess={(email) => handleLogin({
          id: 'usr-1',
          email,
          fullName: profile.fullName || 'Алексей Смирнов',
          occupation: profile.occupation || 'Дизайнер интерфейсов & UI/UX',
          profession: profile.profession || 'designer',
          isSelfEmployed: true
        })}
        onNavigate={navigateTo}
      />
    );
  }

  if (activeRoute === '/register') {
    return (
      <RegisterView
        onRegister={handleLogin}
        onRegisterSuccess={(newProf) => {
          setProfile(newProf);
          handleLogin({
            id: newProf.id || 'usr-1',
            email: newProf.email,
            fullName: newProf.fullName,
            occupation: newProf.occupation,
            profession: newProf.profession,
            isSelfEmployed: newProf.isSelfEmployed
          });
        }}
        onNavigate={navigateTo}
      />
    );
  }

  // Main Authenticated Application Workspace
  const selectedInvoice = invoices.find((i) => i.id === selectedInvoiceId) || invoices[0];
  const unpaidCount = invoices.filter((i) => i.status === 'issued' || i.status === 'overdue').length;
  const activeTasksCount = tasks.filter((t) => t.status !== 'done' && t.status !== 'completed').length;

  return (
    <div className="min-h-screen bg-[var(--bg-main)] text-[var(--text-primary)] font-sans flex antialiased">
      {/* Main Leftmost Sidebar - firmly docked to the left edge */}
      <Sidebar
        currentRoute={activeRoute}
        onNavigate={navigateTo}
        unpaidCount={unpaidCount}
        tasksCount={activeTasksCount}
      />

      {/* Workspace Area: Navbar + Content */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden bg-[var(--bg-main)]">
        <Navbar
          user={currentUser}
          userProfile={profile}
          tasks={tasks}
          invoices={invoices}
          clients={clients}
          isDarkMode={isDarkMode}
          onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
          currentRoute={activeRoute}
          onNavigate={navigateTo}
          onLogout={handleLogout}
        />

        {/* Scrollable Page Body */}
        <main className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8 bg-[var(--bg-main)]">
          {activeRoute === '/dashboard' && (
            <DashboardView
              userProfile={profile}
              invoices={invoices}
              clients={clients}
              events={events}
              tasks={tasks}
              logs={activityLogs}
              activityLogs={activityLogs}
              onNavigate={navigateTo}
              onQuickCreateInvoice={() => navigateTo('/invoices/create')}
              isDarkMode={isDarkMode}
            />
          )}

          {activeRoute === '/invoices' && (
            <InvoicesView
              invoices={invoices}
              userProfile={profile}
              onNavigate={navigateTo}
              onDeleteInvoice={handleDeleteInvoice}
              onDuplicateInvoice={handleDuplicateInvoice}
              onMarkPaid={handleMarkPaid}
            />
          )}

          {activeRoute.startsWith('/invoices/edit/') && (
            <InvoiceFormView
              invoice={invoices.find((i) => i.id === activeRoute.split('/invoices/edit/')[1])}
              clients={clients}
              userProfile={profile}
              templates={templates}
              onSave={handleSaveInvoice}
              onCancel={() => navigateTo('/invoices')}
              onNavigate={navigateTo}
            />
          )}

          {activeRoute === '/invoices/create' && (
            <InvoiceFormView
              clients={clients}
              userProfile={profile}
              templates={templates}
              onSave={handleSaveInvoice}
              onCancel={() => navigateTo('/invoices')}
              onNavigate={navigateTo}
            />
          )}

          {activeRoute.startsWith('/invoices/') && !activeRoute.includes('create') && !activeRoute.includes('edit') && (
            <InvoiceDetailView
              invoice={selectedInvoice}
              userProfile={profile}
              onNavigate={navigateTo}
              onMarkPaid={handleMarkPaid}
            />
          )}

          {activeRoute === '/clients' && (
            <ClientsView
              clients={clients}
              invoices={invoices}
              onAddClient={(c) => handleSaveClient(c)}
              onUpdateClient={(c) => handleSaveClient(c)}
              onDeleteClient={handleDeleteClient}
              onNavigate={navigateTo}
            />
          )}

          {activeRoute === '/tasks' && (
            <TasksView
              tasks={tasks}
              clients={clients}
              onSaveTask={handleSaveTask}
              onUpdateTask={handleUpdateTask}
              onDeleteTask={handleDeleteTask}
            />
          )}

          {activeRoute === '/calendar' && (
            <CalendarView
              events={events}
              clients={clients}
              invoices={invoices}
              onSaveEvent={handleSaveEvent}
              onDeleteEvent={handleDeleteEvent}
            />
          )}

          {activeRoute === '/taxes' && (
            <TaxCalculatorView
              invoices={invoices}
              userProfile={profile}
              taxData={taxData}
            />
          )}

          {activeRoute === '/analytics' && (
            <AnalyticsView
              clients={clients}
              invoices={invoices}
              templates={templates}
            />
          )}

          {activeRoute === '/devtools' && (
            <DevToolsView />
          )}

          {activeRoute === '/reports' && (
            <ReportsView
              invoices={invoices}
              clients={clients}
              userProfile={profile}
              isDarkMode={isDarkMode}
            />
          )}

          {activeRoute === '/booking' && (
            <BookingView userProfile={profile} />
          )}

          {activeRoute === '/settings' && (
            <SettingsView
              userProfile={profile}
              profile={profile}
              onSaveProfile={handleSaveProfile}
              onUpdateProfile={handleSaveProfile}
              onResetData={handleResetData}
              isDarkMode={isDarkMode}
              onToggleDarkMode={() => setIsDarkMode(!isDarkMode)}
            />
          )}
        </main>
      </div>

      {/* Floating Keyboard Sequence Helper HUD - Mathematically aligned on single baseline */}
      {sequenceActive && (
        <div className="fixed bottom-6 right-6 z-50 bg-[#1E293B] text-white px-4 py-2.5 rounded-2xl shadow-2xl border border-slate-700/80 flex items-center space-x-3 text-xs font-bold animate-in fade-in slide-in-from-bottom-2 select-none max-w-[90vw] overflow-x-auto">
          <div className="flex items-center space-x-2 shrink-0">
            <div className="w-6 h-6 flex items-center justify-center shrink-0">
              <kbd className="w-6 h-6 flex items-center justify-center rounded-md bg-amber-500 text-slate-950 font-black font-mono text-xs leading-none shadow-xs">
                {sequenceKey?.toUpperCase()}
              </kbd>
            </div>
            <span className="text-slate-300 font-semibold leading-none">{t('hud.press')}:</span>
          </div>
          <div className="flex items-center space-x-3 whitespace-nowrap">
            {[
              { k: 'D', l: t('hud.overview') || 'Обзор' },
              { k: 'I', l: t('hud.invoices') || 'Счета' },
              { k: 'C', l: t('hud.clients') || 'Клиенты' },
              { k: 'T', l: t('hud.tasks') || 'Задачи' },
              { k: 'K', l: 'Календарь' },
              { k: 'X', l: 'НПД' },
              { k: 'E', l: 'IT-Tools' },
              { k: 'A', l: 'Аналитика' },
              { k: 'R', l: 'Отчеты' },
              { k: 'S', l: 'Настройки' },
              { k: '?', l: 'Справка' }
            ].map(hk => (
              <span key={hk.k} className="inline-flex items-center space-x-1.5 shrink-0">
                <div className="flex items-center justify-center shrink-0">
                  <kbd className="px-1.5 h-5 flex items-center justify-center rounded bg-slate-800 border border-slate-600 text-amber-400 font-mono text-[11px] font-black leading-none shadow-xs">
                    {hk.k}
                  </kbd>
                </div>
                <span className="text-slate-300 text-[11px] font-medium leading-none">{hk.l}</span>
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Keyboard Shortcuts Reference Modal */}
      <KeyboardShortcutsModal
        isOpen={isShortcutsOpen}
        onClose={() => setIsShortcutsOpen(false)}
      />
    </div>
  );
};

export const App: React.FC = () => {
  return (
    <LocalizationProvider>
      <MainAppContent />
    </LocalizationProvider>
  );
};

export default App;
