export type Profession = 'designer' | 'developer' | 'copywriter' | 'marketer' | 'freelancer' | 'other' | string;

export type CurrencyCode = 'RUB' | 'USD' | 'EUR' | 'KZT' | 'BYN' | 'CNY';

export type InvoiceStatus = 'draft' | 'issued' | 'sent' | 'paid' | 'overdue';

export type ClientType = 'individual' | 'legal';

export type ClientStatus = 'active' | 'archived' | 'lead';

export type TaskStatus = 'todo' | 'in_progress' | 'review' | 'done' | 'completed';

export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

export type EventType = 'meeting' | 'call' | 'deadline' | 'invoice';

export interface AuthUser {
  id: string;
  email: string;
  fullName: string;
  occupation: string;
  profession?: Profession;
  isSelfEmployed?: boolean;
}

export interface BankDetails {
  bankName: string;
  bik: string;
  accountNumber: string;
  corrAccount?: string;
}

export interface UserProfile {
  id: string;
  email: string;
  fullName: string;
  occupation: string;
  profession?: Profession;
  customProfession?: string;
  isSelfEmployed: boolean;
  inn: string;
  phone: string;
  region?: string;
  city?: string;
  avatar?: string;
  socialLinks?: {
    telegram?: string;
    website?: string;
    github?: string;
    behance?: string;
  };
  bankDetails: BankDetails;
  currency?: CurrencyCode;
  invoiceSettings?: {
    logoUrl?: string;
    stampUrl?: string;
    currency?: CurrencyCode;
    defaultNotes: string;
    paymentInstructions?: string;
    colorTheme?: string;
    defaultVatRate?: number;
    prefix?: string;
    nextNumber?: number;
  };
}

export type RecurringFrequency = 'weekly' | 'monthly' | 'quarterly';

export interface ClientNote {
  id: string;
  title?: string;
  content: string;
  category?: 'meeting' | 'call' | 'remark' | 'agreement' | 'summary';
  createdAt: string;
}

export interface Client {
  id: string;
  name: string;
  type: ClientType; // 'individual' = физлицо (4% tax), 'legal' = юрлицо/ИП (6% tax)
  status?: ClientStatus; // 'active' | 'archived' | 'lead'
  inn?: string;
  email: string;
  phone: string;
  address?: string;
  tags: string[];
  notes?: string;
  meetingNotes?: ClientNote[];
  totalLtv: number;
  createdAt: string;
}

export interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface Invoice {
  id: string;
  number: string;
  date: string;
  dueDate: string;
  clientId: string;
  clientName: string;
  clientType: ClientType;
  clientInn?: string;
  clientEmail?: string;
  items: InvoiceItem[];
  subtotal: number;
  taxRate: number; // 0 for self-employed usually, or VAT
  taxAmount: number; // calculated NPD tax
  total: number;
  status: InvoiceStatus;
  notes?: string;
  paymentLink?: string;
  token?: string;
  publicToken?: string;
  paidAt?: string;
  isRecurring?: boolean;
  recurringFrequency?: RecurringFrequency;
  nextRecurringDate?: string;
  autoGenerateDrafts?: boolean;
  createdAt: string;
  updatedAt?: string;
}

export interface TaskComment {
  id: string;
  authorName: string;
  text: string;
  createdAt: string;
}

export interface SubTask {
  id: string;
  title: string;
  completed: boolean;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  deadline: string;
  dueDate?: string;
  clientId?: string;
  clientName?: string;
  tags?: string[];
  subtasks?: SubTask[];
  estimatedHours?: number;
  loggedHours?: number;
  hourlyRate?: number;
  invoiceId?: string;
  comments?: TaskComment[];
  createdAt: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  description?: string;
  startTime: string; // ISO string or YYYY-MM-DD THH:MM
  endTime: string;
  type: EventType;
  clientId?: string;
  invoiceId?: string;
  reminderSent?: boolean;
  location?: string;
  createdAt: string;
}

export interface TaxReport {
  id: string;
  periodStart: string;
  periodEnd: string;
  individualIncome: number; // 4%
  legalIncome: number;      // 6%
  totalIncome: number;
  tax4Percent: number;
  tax6Percent: number;
  totalTax: number;
  status: 'draft' | 'paid' | 'declared';
  createdAt: string;
}

export interface TaxCalculationResult {
  yearlyIncome: number;
  yearlyLimit: number;
  remainingLimit: number;
  incomeFromIndividuals: number;
  incomeFromLegal: number;
  estimatedTax: number;
  taxDeductionRemaining: number;
  totalIncome?: number;
  taxAmount?: number;
  projectedTax?: number;
}

export interface ActivityLog {
  id: string;
  title: string;
  description: string;
  type: 'invoice' | 'client' | 'task' | 'event' | 'tax';
  timestamp: string;
}

export interface InvoiceTemplate {
  id: string;
  title: string;
  description: string;
  clientType: ClientType;
  items: { description: string; quantity: number; unitPrice: number }[];
}
